#
#  Makefile for the Linux Controller Area Network SPI drivers.
#
obj-$(CONFIG_CAN_MCP25XXFD)	+= mcp25xxfd.o
mcp25xxfd-objs                  := mcp25xxfd_base.o
mcp25xxfd-objs                  += mcp25xxfd_can.o
